from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib import colors
from datetime import datetime
import io
import base64


class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=1
        ))
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            spaceBefore=12
        ))

    def generate_pdf(self, predictions, heatmap_base64, patient_info=None):
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.5*inch,
            leftMargin=0.5*inch,
            topMargin=0.5*inch,
            bottomMargin=0.5*inch
        )

        story = []

        story.append(Paragraph("Chest X-Ray Analysis Report", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.3*inch))

        if patient_info:
            patient_data = [
                ["Patient Name:", patient_info.get('name', 'N/A')],
                ["Patient ID:", patient_info.get('id', 'N/A')],
                ["Analysis Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ]
            patient_table = Table(patient_data, colWidths=[2*inch, 4*inch])
            patient_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ]))
            story.append(patient_table)
        else:
            story.append(Paragraph(
                f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                self.styles['Normal']
            ))

        story.append(Spacer(1, 0.3*inch))

        story.append(Paragraph("Primary Diagnosis", self.styles['CustomHeading']))
        top_label = predictions['top_label']
        top_score = predictions['top_score']
        confidence = f"{top_score * 100:.2f}%"
        story.append(Paragraph(
            f"<b>{top_label}</b> (Confidence: {confidence})",
            self.styles['Normal']
        ))

        story.append(Spacer(1, 0.2*inch))

        story.append(Paragraph("Grad-CAM Heatmap", self.styles['CustomHeading']))
        try:
            heatmap_img = Image(io.BytesIO(base64.b64decode(heatmap_base64)), width=5*inch, height=5*inch)
            story.append(heatmap_img)
        except Exception as e:
            story.append(Paragraph(f"Error displaying heatmap: {str(e)}", self.styles['Normal']))

        story.append(PageBreak())

        story.append(Paragraph("All Predictions", self.styles['CustomHeading']))
        predictions_data = [["Disease", "Confidence"]]
        for label, score in zip(predictions['labels'], predictions['scores']):
            predictions_data.append([label, f"{score * 100:.2f}%"])

        predictions_table = Table(predictions_data, colWidths=[3*inch, 3*inch])
        predictions_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4a90e2')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ]))
        story.append(predictions_table)

        story.append(Spacer(1, 0.3*inch))
        story.append(Paragraph(
            "Note: This report is generated by AI and should be reviewed by a qualified radiologist.",
            self.styles['Normal']
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()
